app = "dealcross-backend"  # replace if your Fly app slug is different

primary_region = "lhr"  # London, adjust if needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"  # match Dockerfile and uvicorn

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200