app = "dealcross-backend"  # ✅ your Fly.io app name

primary_region = "lhr"  # ✅ London region, adjust if needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"  # ✅ FastAPI default

[[services]]
  protocol = "tcp"
  internal_port = 8000  # ✅ match FastAPI PORT

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200