-- This file is auto-generated by Aerich.
-- Do not edit manually unless you know what you’re doing.

CREATE TABLE IF NOT EXISTS "user" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    -- Add more fields according to your model structure
);

-- Repeat for other tables as per your actual models...
-- Normally Aerich generates this, so this placeholder represents your structure